version: '3'
services:
  api:
    container_name: client-api
    image: client-api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: postgres-db-client-api
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer-db
    ports:
      - "5433:5432"
