spring:
  datasource:
    url: jdbc:mysql://172.17.0.3:3306/customer_tb?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin
    devtools:
      remote:
        secret: 123

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true

  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8081